#include <iostream>
#include <fstream>
#include <vector>
#include <string>
#include <cstdint>
#include <algorithm>
#include <iomanip>

// ─────────────────────────────────────────────────────────────────────────────
// Tello Navigator — Map Statistics Parser
// Reads a PNG map generated by grid_map.py and prints cell-level statistics.
//
// Cell colour encoding (matches grid_map.py):
//   #eeeeee  →  EMPTY    (unexplored)
//   #00ff00  →  START    (start position)
//   #aaffaa  →  VISITED  (drone path)
//   #333333  →  WALL     (obstacle / detected wall)
//   #ff0000  →  CURRENT  (drone's last position marker)
// ─────────────────────────────────────────────────────────────────────────────

// ── Minimal PNG reader (no external libs) ────────────────────────────────────
// Reads only uncompressed or zlib-compressed IDAT chunks via a simple inflate.
// For simplicity we use stb_image-style manual IHDR parsing.

#pragma pack(push, 1)
struct PngChunk {
    uint32_t length;
    char     type[4];
};
#pragma pack(pop)


// ── Cell types ───────────────────────────────────────────────────────────────
enum CellType { UNKNOWN = 0, EMPTY, START, VISITED, WALL, CURRENT };

static const char* cell_name(CellType t) {
    switch (t) {
        case EMPTY:   return "Empty (unexplored)";
        case START:   return "Start position";
        case VISITED: return "Visited (drone path)";
        case WALL:    return "Wall / obstacle";
        case CURRENT: return "Current position";
        default:      return "Unknown";
    }
}

// Classify a pixel (r,g,b) → CellType by matching grid_map.py colour palette
static CellType classify_pixel(uint8_t r, uint8_t g, uint8_t b) {
    // #eeeeee — EMPTY
    if (r >= 0xE0 && g >= 0xE0 && b >= 0xE0 && std::abs(r-g)<20 && std::abs(g-b)<20)
        return EMPTY;
    // #00ff00 — START
    if (r == 0x00 && g == 0xFF && b == 0x00)
        return START;
    // #aaffaa — VISITED  (light green)
    if (r >= 0x90 && r <= 0xC0 && g >= 0xF0 && b >= 0x90 && b <= 0xC0)
        return VISITED;
    // #333333 — WALL  (dark grey)
    if (r <= 0x55 && g <= 0x55 && b <= 0x55 && std::abs(r-g)<20 && std::abs(g-b)<20)
        return WALL;
    // #ff0000 — CURRENT (red dot)
    if (r >= 0xE0 && g <= 0x40 && b <= 0x40)
        return CURRENT;

    return UNKNOWN;
}

// ── Load PNG using system libpng via popen trick — use raw PPM instead ───────
// We convert PNG → PPM using python Pillow (already installed on RPi)
// then parse the simple PPM format in pure C++.

bool png_to_ppm(const std::string& png_path, const std::string& ppm_path) {
    std::string cmd = "python3 -c \""
        "from PIL import Image; "
        "img = Image.open('" + png_path + "').convert('RGB'); "
        "img.save('" + ppm_path + "')"
        "\" 2>/dev/null";
    return system(cmd.c_str()) == 0;
}

struct Pixel { uint8_t r, g, b; };

bool load_ppm(const std::string& path,
              std::vector<Pixel>& pixels,
              int& width, int& height)
{
    std::ifstream f(path, std::ios::binary);
    if (!f) return false;

    std::string magic;
    f >> magic;
    if (magic != "P6") return false;

    int maxval;
    f >> width >> height >> maxval;
    f.ignore(1); // single whitespace after header

    pixels.resize(width * height);
    f.read(reinterpret_cast<char*>(pixels.data()), width * height * 3);
    return f.good();
}

// ── Main ─────────────────────────────────────────────────────────────────────
int main(int argc, char* argv[]) {

    std::string png_path = "docs/final_map.png";
    int cell_size_cm = 25;   // default from settings.yaml

    if (argc >= 2) png_path   = argv[1];
    if (argc >= 3) cell_size_cm = std::stoi(argv[2]);

    std::cout << "\n";
    std::cout << "╔══════════════════════════════════════════╗\n";
    std::cout << "║   Tello Navigator — Map Stats Parser     ║\n";
    std::cout << "╚══════════════════════════════════════════╝\n\n";
    std::cout << "Map file  : " << png_path << "\n";
    std::cout << "Cell size : " << cell_size_cm << " cm\n\n";

    // Convert PNG → PPM
    std::string ppm_path = "/tmp/_tello_map.ppm";
    if (!png_to_ppm(png_path, ppm_path)) {
        std::cerr << "Error: Could not convert PNG. Is Pillow installed?\n";
        return 1;
    }

    std::vector<Pixel> pixels;
    int img_w = 0, img_h = 0;
    if (!load_ppm(ppm_path, pixels, img_w, img_h)) {
        std::cerr << "Error: Could not read PPM file.\n";
        return 1;
    }

    // Infer grid size from image dimensions
    // grid_map.py uses 20px per cell
    const int PX_PER_CELL = 20;
    int grid_w = img_w / PX_PER_CELL;
    int grid_h = img_h / PX_PER_CELL;

    std::cout << "Image     : " << img_w << " × " << img_h << " px\n";
    std::cout << "Grid      : " << grid_w << " × " << grid_h << " cells\n";
    std::cout << "Room size : "
              << grid_w * cell_size_cm / 100.0 << " m × "
              << grid_h * cell_size_cm / 100.0 << " m\n\n";

    // Sample centre pixel of each cell → classify
    std::vector<std::vector<CellType>> grid(grid_h, std::vector<CellType>(grid_w));

    int cnt[6] = {};  // counts per CellType

    for (int row = 0; row < grid_h; ++row) {
        for (int col = 0; col < grid_w; ++col) {
            int px = col * PX_PER_CELL + PX_PER_CELL / 2;
            int py = row * PX_PER_CELL + PX_PER_CELL / 2;
            if (px >= img_w || py >= img_h) continue;

            Pixel p = pixels[py * img_w + px];
            CellType t = classify_pixel(p.r, p.g, p.b);
            grid[row][col] = t;
            cnt[t]++;
        }
    }

    int total = grid_w * grid_h;
    int indoor = total - cnt[EMPTY] - cnt[UNKNOWN]; // cells inside the room
    int visited_total = cnt[VISITED] + cnt[START] + cnt[CURRENT];

    // ── Print stats ──────────────────────────────────────────────────────
    std::cout << "─── Cell counts ─────────────────────────────\n";
    const CellType types[] = { VISITED, WALL, EMPTY, START, CURRENT, UNKNOWN };
    for (CellType t : types) {
        if (cnt[t] == 0) continue;
        std::cout << "  " << std::left << std::setw(24) << cell_name(t)
                  << std::right << std::setw(5) << cnt[t] << " cells\n";
    }

    std::cout << "\n─── Coverage ────────────────────────────────\n";
    std::cout << "  Total grid cells : " << total << "\n";
    std::cout << "  Indoor cells     : " << indoor << "\n";

    if (indoor > 0) {
        double cov = 100.0 * visited_total / indoor;
        std::cout << "  Visited          : " << visited_total
                  << "  (" << std::fixed << std::setprecision(1) << cov << "%)\n";
    }

    double area_m2 = (double)visited_total * cell_size_cm * cell_size_cm / 10000.0;
    std::cout << "  Area covered     : " << std::fixed << std::setprecision(2)
              << area_m2 << " m²\n";

    std::cout << "\n─── ASCII preview ───────────────────────────\n";
    // Print a scaled-down ASCII map (max 60 chars wide)
    int step = std::max(1, grid_w / 60);
    for (int row = 0; row < grid_h; row += step) {
        std::cout << "  ";
        for (int col = 0; col < grid_w; col += step) {
            switch (grid[row][col]) {
                case WALL:    std::cout << "█"; break;
                case VISITED: std::cout << "·"; break;
                case START:   std::cout << "S"; break;
                case CURRENT: std::cout << "X"; break;
                default:      std::cout << " "; break;
            }
        }
        std::cout << "\n";
    }

    std::cout << "\n  Legend: █=wall  ·=visited  S=start  X=current pos\n\n";

    return 0;
}
